export const cuisines = [
  { id: 0, value: "African" },
  { id: 1, value: "Asian" },
  { id: 2, value: "American" },
  { id: 3, value: "British" },
  { id: 4, value: "Cajun" },
  { id: 5, value: "Caribbean" },
  { id: 6, value: "Chinese" },
  { id: 7, value: "Eastern European" },
  { id: 8, value: "European" },
  { id: 9, value: "French" },
  { id: 10, value: "German" },
  { id: 11, value: "Greek" },
  { id: 12, value: "Indian" },
  { id: 13, value: "Irish" },
  { id: 14, value: "Italian" },
  { id: 15, value: "Japanese" },
  { id: 16, value: "Jewish" },
  { id: 17, value: "Korean" },
  { id: 18, value: "Latin American" },
  { id: 19, value: "Mediterranean" },
  { id: 20, value: "Mexican" },
  { id: 21, value: "Middle Eastern" },
  { id: 22, value: "Nordic" },
  { id: 23, value: "Southern" },
  { id: 24, value: "Spanish" },
  { id: 25, value: "Thai" },
  { id: 26, value: "Vietnamese" },
];
