export const cuisines = [
  { id: 0, value: "African", icon: "🌍", isSelected: false },
  { id: 1, value: "Asian", icon: "🍜", isSelected: false },
  { id: 2, value: "American", icon: "🍔", isSelected: false },
  { id: 3, value: "British", icon: "🇬🇧", isSelected: false },
  { id: 4, value: "Cajun", icon: "🌶️", isSelected: false },
  { id: 5, value: "Caribbean", icon: "🏝️", isSelected: false },
  { id: 6, value: "Chinese", icon: "🥡", isSelected: false },
  { id: 7, value: "Eastern European", icon: "🇪🇺", isSelected: false },
  { id: 8, value: "European", icon: "🌍", isSelected: false },
  { id: 9, value: "French", icon: "🥖", isSelected: false },
  { id: 10, value: "German", icon: "🥨", isSelected: false },
  { id: 11, value: "Greek", icon: "🇬🇷", isSelected: false },
  { id: 12, value: "Indian", icon: "🍛", isSelected: false },
  { id: 13, value: "Irish", icon: "🍀", isSelected: false },
  { id: 14, value: "Italian", icon: "🍕", isSelected: false },
  { id: 15, value: "Japanese", icon: "🍣", isSelected: false },
  { id: 16, value: "Jewish", icon: "🕍", isSelected: false },
  { id: 17, value: "Korean", icon: "🇰🇷", isSelected: false },
  { id: 18, value: "Latin American", icon: "🌮", isSelected: false },
  { id: 19, value: "Mediterranean", icon: "🍅", isSelected: false },
  { id: 20, value: "Mexican", icon: "🌶️", isSelected: false },
  { id: 21, value: "Middle Eastern", icon: "🧆", isSelected: false },
  { id: 22, value: "Nordic", icon: "❄️", isSelected: false },
  { id: 23, value: "Southern", icon: "🍗", isSelected: false },
  { id: 24, value: "Spanish", icon: "🍷", isSelected: false },
  { id: 25, value: "Thai", icon: "🍲", isSelected: false },
  { id: 26, value: "Vietnamese", icon: "🍜", isSelected: false },
];
