"use client";
import { Kanit } from "next/font/google";
import store from "@/redux/store";
import { Provider } from "react-redux";
// export const metadata = {
//   title: 'Fast Cook',
//   description: 'Generated by Hakan Karaahmetoglu',
// }

const kanit = Kanit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
