import { Kanit } from "next/font/google";
import "./global.css";
import Navbar from "../components/Navbar";
import classNames from "classnames";
import Footer from "../components/Footer";
import { Providers } from "../redux/provider";

//ESLINT UYGULANACAK

const kanit = Kanit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Fast Cook",
  description: "Fast-cook, generated by Hakan Karaahmetoglu",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body
          className={classNames(
            "text-mainText min-h-screen flex flex-col  gradient-background ",
            kanit.className
          )}
        >
          <Navbar />
          {children}
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
